### ISSUE TITLE
when filtering on SDGs the field `id` is not defined on a record. 

### ISSUE THREAD

**Issue by phish108** [sustainability-zhaw/sustainability-dashboard#85]
```
records.mjs:121 Uncaught TypeError: Cannot read properties of undefined (reading 'id')
    at records.mjs:121:68
    at Array.sort (<anonymous>)
    at records.mjs:121:39
    at Array.reduce (<anonymous>)
    at records.mjs:97:45
    at Array.reduce (<anonymous>)
    at HTMLDivElement.renderRecords (records.mjs:96:22)
    at a.<computed> [as dataUpdate] (Events.mjs:34:44)
    at fetchData (Data.mjs:70:24)
    at async HTMLDivElement.handleLoadData (Data.mjs:48:5)
```

**Comment by phish108** [comment]
this is fixed with commit [72fcaa9](https://github.com/sustainability-zhaw/sustainability-dashboard/commit/72fcaa9e2fa8b83fa749a747f616ef4cad0046ef)
